
# 槽增强描述
slot_descs = {
    "hotel-pricerange": "pricerange of the hotel",
    "hotel-type": "type of the hotel",
    "hotel-parking": "whether have parking in the hotel",
    "hotel-book stay": "number of stay for the hotel booking",
    "hotel-book day": "day for the hotel booking",
    "hotel-book people": "number of people for the hotel booking",
    "hotel-area": "area of the hotel",
    "hotel-stars": "number of stars of the hotel",
    "hotel-internet": "whether have internet in the hotel",
    "hotel-name": "name of the hotel",
    "train-destination": "location of destination of the train",
    "train-day": "day of the train",
    "train-departure": "location of departure of the train",
    "train-arriveBy": "time of arrive by of the train",
    "train-book people": "number of people for the train booking",
    "train-leaveAt": "time of leave at of the train",
    "attraction-type": "type of attraction",
    "attraction-area": "area of attraction",
    "attraction-name": "name of attraction",
    "restaurant-book people": "number of people for the restaurant booking",
    "restaurant-book day": "day for the restaurant booking",
    "restaurant-book time": "time for the restaurant booking",
    "restaurant-food": "food of the restaurant",
    "restaurant-pricerange": "pricerange of the restaurant",
    "restaurant-name": "name of the restaurant",
    "restaurant-area": "area of the restaurant",
    "taxi-leaveAt": "time of leave at of the taxi",
    "taxi-destination": "location of destination of the taxi",
    "taxi-departure": "location of departure of the taxi",
    "taxi-arriveBy": "time of arrive by of the taxi",
}

# slot_descs = {
#     "hotel-pricerange": "hotel price range",
#     "hotel-type": "hotel type",
#     "hotel-parking": "hotel parking",
#     "hotel-book stay": "hotel book",
#     "hotel-book day": "hotel day",
#     "hotel-book people": "hotel book people",
#     "hotel-area": "hotel area",
#     "hotel-stars": "hotel stars",
#     "hotel-internet": "hotel internet",
#     "hotel-name": "hotel name",
#     "train-destination": "train destination",
#     "train-day": "train day",
#     "train-departure": "train departure",
#     "train-arriveBy": "train arrive by",
#     "train-book people": "train book people",
#     "train-leaveAt": "train leave at",
#     "attraction-type": "attraction type",
#     "attraction-area": "attraction area",
#     "attraction-name": "attraction name",
#     "restaurant-book people": "restaurant book people",
#     "restaurant-book day": "restaurant book day",
#     "restaurant-book time": "restaurant book time",
#     "restaurant-food": "restaurant food",
#     "restaurant-pricerange": "restaurant price range",
#     "restaurant-name": "restaurant name",
#     "restaurant-area": "restaurant area",
#     "taxi-leaveAt": "taxi leave at",
#     "taxi-destination": "taxi destination",
#     "taxi-departure": "taxi departure",
#     "taxi-arriveBy": "taxi arrive",
# }